### ISSUE TITLE
cassandre-trading-bot integrate with Okex, Request customizable getOpenOrders method in TradeServiceXChangeImplementation class

### ISSUE THREAD

**Issue by huahouye** [cassandre-tech/cassandre-trading-bot#712]
**Is your feature request related to a problem? Please describe.**

I have tried to integrate both cassandre-trading-bot and Okex API v3, but failed. Because [TradeServiceXChangeImplementation#getOrders()](https://github.com/cassandre-tech/cassandre-trading-bot/blob/5.0.2/spring-boot-starter/autoconfigure/src/main/java/tech/cassandre/trading/bot/service/TradeServiceXChangeImplementation.java#L280) cannot handle Okex Exchange API, since [xchange-okcoin OkexTradeService#getOpenOrders()](https://github.com/knowm/XChange/blob/develop/xchange-okcoin/src/main/java/org/knowm/xchange/okcoin/v3/service/OkexTradeService.java#L119) throws NotAvailableFromExchangeException directly, but `OkexTradeService#getOpenOrders(OpenOrdersParams params)` works.

**Describe the solution you'd like**

So I think if CTB could privide a customized point in `TradeServiceXChangeImplementation` class that I can write corresponding implementation for diffrent Exchange. at least makes `TradeServiceXChangeImplementation#getOrders()` works then makes `OrderFlux` works well.

here is my solution draft:

1. create a FunctionalInterface

```
@FunctionalInterface
public interface GetOpenOrdersCustomizer {
	OpenOrders getOpenOrders();
}
```

2. then CTB can privides a default bean for GetOpenOrdersCustomized

```
@Bean
@ConditionalOnMissingBean(GetOpenOrdersCustomizer.class)
public GetOpenOrdersCustomizer getOpenOrdersCustomizer(org.knowm.xchange.service.trade.TradeService xChangeTradeService) {
    return () -> {
        try {
            return xChangeTradeService.getOpenOrders();
        } catch (IOException e) {
            logger.error("Error retrieving orders: {}", e.getMessage());
            return new OpenOrders(Collections.emptyList());
        }
    };
}
```

3. I also can replace it with mine

```
@Bean
public getOpenOrdersCustomizer getOpenOrdersCustomizer(org.knowm.xchange.service.trade.TradeService xChangeTradeService) {
    return () -> {
        try {
            DefaultOpenOrdersParamCurrencyPair param = new DefaultOpenOrdersParamCurrencyPair(CurrencyPair.BTC_USDT);
            // for-loop etc.
            return xChangeTradeService.getOpenOrders(param);
        } catch (IOException e) {
            logger.error("Error retrieving orders: {}", e.getMessage());
            return new OpenOrders(Collections.emptyList());
        }
    };
}
```

4. injected getOpenOrdersCustomizer bean into TradeServiceXChangeImplementation and use it

replace [tradeService.getOpenOrders()](https://github.com/cassandre-tech/cassandre-trading-bot/blob/5.0.2/spring-boot-starter/autoconfigure/src/main/java/tech/cassandre/trading/bot/service/TradeServiceXChangeImplementation.java#L280) with `getOpenOrdersCustomizer.getOpenOrders()`

**Additional context**

the main problem is this solution will impact a lot of codes, like refactor the main workflow. It may not be a good one.

**Comment by straumat** [comment]
@huahouye Hi ! I plan to fully test (on real exchange) Okex so I will take a look at the problem. From my experience with XChange, I can add the parameter OpenOrdersParams and it will still work with other exchanges. I will try to add it quickly

**Comment by straumat** [comment]
@huahouye when starting Cassandre with a Okex account, i get an error that says that getAccountInfo is not yet implemented, do you have the same error ?

**Comment by huahouye** [comment]
@straumat `getAccountInfo` works in my project, do you use `org.knowm.xchange.okcoin.OkexExchangeV3`? if not, I think it may be because xchange does not implement Okex API V5 yet by now. Maven dependency should use `xchange-okcoin` not `xchange-okex`:

```
<dependency>
	<groupId>org.knowm.xchange</groupId>
	<artifactId>xchange-okcoin</artifactId>
	<version>5.0.9</version>
</dependency>
```

`application.yml` config file looks like this:

```
cassandre:
  trading:
    bot:
      exchange:
        # okex api v5 ## xchange 2021-08-09 还未完全实现
        # driver-class-name: org.knowm.xchange.okex.v5.OkexExchange
        # key: 09c63xxxab5e99
        # secret: 84BDxxx0A9F80D
        # passphrase: t95xxx
        #
        # okex api v3 works
        driver-class-name: org.knowm.xchange.okcoin.OkexExchangeV3
        key: 2034xxx63
        secret: F9FC6xxx8F5
        passphrase: fC6xxx
        #
        username: "kucoin.cassandre.test@gmail.com"
        # Exchange API calls rates (ms or standard ISO 8601 duration like 'PT5S').
        rates:
          account: 5000
          ticker: 5000
          trade: 5000
        proxy-host: "127.0.0.1" ##
        proxy-port: 1087 ##
        modes:
          dry: false
          sandbox: false
```

`SimpleStrategy` looks like this:

```
@CassandreStrategy(strategyName = "Simple strategy")
public final class SimpleStrategy extends BasicCassandreStrategy {

	@Override
	public Set<CurrencyPairDTO> getRequestedCurrencyPairs() {
		// We only ask about ETC/BTC (Base currency : BTC / Quote currency : USDT).
		return Set.of(new CurrencyPairDTO(BTC, USDT));
	}

	@Override
	public Optional<AccountDTO> getTradeAccount(Set<AccountDTO> accounts) {
		
		logger.debug("get all accounts: {}", accounts);
		
		// From all the accounts retrieved by the server, we return the one we used for trading.
		if (accounts.size() == 1) {
			return accounts.stream().findAny();
		} else {
			return accounts.stream()
					.filter(a -> "Trading".equals(a.getName())) // *** name of trading account is `Trading` not `trade` for okex api 
					.findFirst();
		}
	}
}
```
